name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_leapYear
      id: test_leapyear
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_leapYear
        setup-command: ''
        command: python3 test_main.py
        timeout: 2
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_LEAPYEAR_RESULTS: "${{steps.test_leapyear.outputs.result}}"
      with:
        runners: test_leapyear
